### ISSUE TITLE
Redirect www. to non-www. domain for heroku?

### ISSUE THREAD

**Issue by ghost** [cloudhead/toto#1]

**Comment by ghost** [comment]
Ok solved. Put this code in config:

```
gem 'rack-rewrite', '~> 0.2.1'
require 'rack-rewrite'
    if ENV['RACK_ENV'] == 'production'
        use Rack::Rewrite do
         r301 %r{.*}, 'http://yoursite.com$&', :if => Proc.new {|rack_env|
        rack_env['SERVER_NAME'] != 'yoursite.com'
        }
    end
end
```

**Comment by cloudhead** [comment]
I've decided this shouldn't be part of core, so I added a wiki entry with your config:

http://wiki.github.com/cloudhead/toto/url-rewriting

**Comment by vincentwoo** [comment]
Or just use the NoWWW gem and in config.ru

```
use Rack:NoWWW
```

**Comment by baopham** [comment]
If i understand it correctly, I think now we can just do `heroku domains:add www.yoursite.com` (https://devcenter.heroku.com/articles/custom-domains)
