### ISSUE TITLE
The Rakefile tasks should have a 'desc' before each rake task so they show up with 'rake -T'

### ISSUE THREAD

**Issue by grempe** [cloudhead/toto#11]
The Rakefile tasks should have a 'desc' before each rake task so they show up with 'rake -T'

Otherwise, running 'rake -T' results in nothingness.

e.g.

```
desc "Create a new post"
task :new do
...
```

**Comment by cloudhead** [comment]
Yea, the Rakefile needs some work, kind of a stub right now.

**Comment by grempe** [comment]
I sent you a pull request addressing this and a couple of other things in the rakefile.

**Comment by cloudhead** [comment]
Pulled in, thanks.
