### ISSUE TITLE
File not found: index.html

### ISSUE THREAD

**Issue by pinkusdinkus** [cloudhead/toto#111]
I was updating my Gemfile now all of a sudden it wont render the root page /
articles seem to show up fine, just the main page wont.
Any ideas?

**Comment by ajaswa** [comment]
I ran into this the other day, downgrading Rack to 1.3.5 seems to fix it. Checkout: https://github.com/rack/rack/issues/301

**Comment by pinkusdinkus** [comment]
aye carumba! Thx that fixed it....  BTW works on 1.3.6 too.
