### ISSUE TITLE
HTML tags are ignored

### ISSUE THREAD

**Issue by siecledeslumieres** [cloudhead/toto#115]
I have a problem with the HTML tags `</body>` and `</html>`, who disappear once my blog is online : http://solenne.heroku.com/

This is the original code :

```
<footer>
powered by <a href="http://cloudhead.io/toto">toto</a>
</footer>
</body>
</html>
```

![GitHub Logo](http://i.stack.imgur.com/Cwufg.png)

And here's the problem when my blog is online :

```
<footer>
powered by <a href="http://cloudhead.io/toto">toto</a>
</footer>
</ 
```

The blog use the template http://github.com/cloudhead/dorothy. The problem happens without a reason when I start to edit the HTML code of the template.

Any help would be greatly appreciated !

**Comment by EtienneLem** [comment]
Can you post your `index.rhtml` html.
Since your post pages are fine, it must be from your `index.rhtml` page.

Maybe it's missing a closing tag?

**Comment by siecledeslumieres** [comment]
Thank you Etienne !

Here is the `index.rhtml` http://i.imgur.com/mUMiN.png

```
<% for article in articles[0...3] %>
<article>
<h1><a href="<%= article.path %>"><%= article.title %></a></h1>
<%= article.summary %>
<div class="more"><a href="<%= article.path %>">read on &raquo;</a></div>
</article>
<% end %>
```

I didn't change anything else that the rhtml pages. But, I notice that [the post I added](http://solenne.heroku.com/2012/03/17/bienvenue/) has the same problem whereas [the default post](http://solenne.heroku.com/1900/05/17/the-wonderful-wizard-of-oz/) has no problem... I admit I still struggle on how to properly upload posts. But, I added this post with the commands [learned here](http://fadeyev.net/2010/05/10/getting-started-with-toto/) :

```
git add .
git commit -a -m "written some new articles"
git push heroku master
```

![GitHub Logo](http://i.imgur.com/m1zA4.png)

Here is the `article.rhtml` http://i.imgur.com/EJMOw.png
The problem is probably a little detail that is the cause of everything, but which one ?!

**Comment by iammichiel** [comment]
Try downgrading Heroku. By default, Heroku creates a stack based on 1.9.x whilst toto was designed on 1.8.x. 
You can downgrade simply using the following : 

```
heroku stack:migrate bamboo-ree-1.8.7
... 
heroku push
```

**Comment by siecledeslumieres** [comment]
Perfect solution Zenklys !!! Thank you so much ! :-)
