### ISSUE TITLE
Invalid ATOM Xml using default builder

### ISSUE THREAD

**Issue by LBRapid** [cloudhead/toto#120]
I noticed that while most feed readers are able to subscribe to my atom feed, it is malformed and causes site's like feedburner to be unable to parse it.

The xml in question is http://www.johndesu.com/index.xml and chrome/feedburner show the following error while parsing it.

```
  error on line 31 at column 11: expected '>'
```

I'm a bit clueless when it comes to xml, so not really sure where to go. Though I'd ask here first.

Cheers

**Comment by baopham** [comment]
I open your link on chrome and firefox and it doesn't give me any errors though

**Comment by LBRapid** [comment]
I switched the Heroku stack I was using and it resolved the issue. Should have updated here too. I'll close the issue.
