### ISSUE TITLE
not working on heroku cedar?

### ISSUE THREAD

**Issue by ndreckshage** [cloudhead/toto#126]
not letting me install on heroku cedar? works find on bamboo.

Heroku push rejected, no Cedar-supported app detected

To git@heroku.com:furious-wind-1923.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:furious-wind-1923.git'

what needs to be done to get this working with more recent version of heroku?

**Comment by cable729** [comment]
This has been happening to me as well

**Comment by AndrewKvalheim** [comment]
I tested prior to deployment using [Foreman](https://devcenter.heroku.com/articles/procfile#developing_locally_with_foreman), which required [creating a simple Procfile](https://github.com/AndrewKvalheim/Andrew.Kvalhe.im/commit/d0a03635da4cd5565808850a15a0818e8cbac57c), and the initial push ran flawlessly. Heroku's documentation [claims](https://devcenter.heroku.com/articles/ruby#declare_process_types_with_foremanprocfile):

> Cedar will recognize any app with a `config.ru` as a Rack app and generate a web process type for you.

but I wonder whether defining processes explicitly might still help your situation.

**Comment by ndreckshage** [comment]
to rephrase -- toto works fine, any template works after converting .gems into Gemfile

**Comment by cable729** [comment]
Sorry for taking so long to respond. I have tried various approaches. Here's my gemfile:

```
source 'http://rubygems.org'
gem 'rack'
gem 'builder'
gem 'rdiscount'
gem 'toto'
```

That's the only thing I've changed. I.E. I have cloned dorothy, created the gemfile, created the heroku app, commited to git, and then tried to push.

```
-----> Heroku receiving push
 !     Heroku push rejected, no Cedar-supported app detected

To git@heroku.com:cjares-toto.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:cjares-toto.git'
```

**Comment by ndreckshage** [comment]
hmm...

save your Gemfile like you have it, run

$ bundle install
$ git init
$ git add .
$ git commit -am 'test'
$ git remote -v
(remove any listed with git rm... ---- just to start over)
$ heroku create
$ git push heroku master

this should work let me know if you still have problems

**Comment by cable729** [comment]
No, it didn't work. Same error :/
Is this correct?

`ruby -v
ruby 1.9.3p194 (2012-04-20) [i386-mingw32]`

**Comment by ndreckshage** [comment]
im using ruby -v 1.9.3p125 but dont think that should make a difference...

do you see the blog @ localhost:9393 if you run $ shotgun ($ gem install shotgun if not installed)

heres my full output --->

$ cd Desktop
$ git clone git://github.com/cloudhead/dorothy.git tototest
Cloning into tototest...
remote: Counting objects: 202, done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 202 (delta 89), reused 179 (delta 81)
Receiving objects: 100% (202/202), 20.70 KiB, done.
Resolving deltas: 100% (89/89), done.
$ cd tototest
$ rm .gems
$ touch Gemfile
$ open Gemfile (then save with --->)
       source 'https://rubygems.org'

```
   gem 'toto'
   gem 'rack'
   gem 'builder'
   gem 'rdiscount'
```

$ bundle install
Fetching gem metadata from https://rubygems.org/..
Using builder (3.0.0) 
Using rack (1.4.1) 
Using rdiscount (1.6.8) 
Using toto (0.4.9) 
Using bundler (1.1.4) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
$ git add .
$ git commit -am 'test'
[master 245a44b] test
 4 files changed, 25 insertions(+), 4 deletions(-)
 create mode 100644 .DS_Store
 delete mode 100644 .gems
 create mode 100644 Gemfile
 create mode 100644 Gemfile.lock
$ heroku create ndtototest
Creating ndtototest... done, stack is cedar
http://ndtototest.herokuapp.com/ | git@heroku.com:ndtototest.git
Git remote heroku added
$ git push heroku master
Counting objects: 207, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (103/103), done.
Writing objects: 100% (207/207), 21.65 KiB, done.
Total 207 (delta 89), reused 202 (delta 89)

-----> Heroku receiving push
-----> Removing .DS_Store files
-----> Ruby/Rack app detected
-----> Installing dependencies using Bundler version 1.2.0.pre
       Running: bundle install --without development:test --path vendor/bundle --binstubs bin/ --deployment
       Fetching gem metadata from https://rubygems.org/..
       Installing builder (3.0.0)
       Installing rack (1.4.1)
       Installing rdiscount (1.6.8) with native extensions
       Installing toto (0.4.9)
       Using bundler (1.2.0.pre)
       Your bundle is complete! It was installed into ./vendor/bundle
       Cleaning up the bundler cache.
-----> Discovering process types
       Procfile declares types     -> (none)
       Default types for Ruby/Rack -> console, rake, web
-----> Compiled slug size is 1.2MB
-----> Launching... done, v3
       http://ndtototest.herokuapp.com deployed to Heroku

To git@heroku.com:ndtototest.git
- [new branch]      master -> master
  $ heroku open
  Opening http://ndtototest.herokuapp.com/

**Comment by cable729** [comment]
I get an error running shotgun:

```
C:\git\toto-blog [master]> shotgun
C:/Ruby193/lib/ruby/gems/1.9.1/gems/shotgun-0.9/bin/shotgun:142:in `trap': unsupported signal SIGQUIT (ArgumentError)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/shotgun-0.9/bin/shotgun:142:in `block in <top (required)>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/shotgun-0.9/bin/shotgun:141:in `each'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/shotgun-0.9/bin/shotgun:141:in `<top (required)>'
        from C:/Ruby193/bin/shotgun:23:in `load'
        from C:/Ruby193/bin/shotgun:23:in `<main>'
```

**Comment by ndreckshage** [comment]
do you have all the required gems locally? do gem install for all the ones toto needs to make sure. past that check out this site and maybe switch your rvm and make sure you have everything up to date

railsinstaller.org

**Comment by cable729** [comment]
Uninstalling all Ruby/related things and reinstalling with the rails installer worked. I also had to delete my heroku app, git clone, whole folder and start over. It also looks like Gemfile has to be capitalized. Either that or my old gemfile was just a little bit off. I have no idea, this was really weird. Thanks for the help, though! Glad to have it working.
