### ISSUE TITLE
10 second blog example can be compressed/improved a bit

### ISSUE THREAD

**Issue by grempe** [cloudhead/toto#14]
See : http://cloudhead.io/toto

First, end users should probably be encouraged to create a fork of the dorothy repo before cloning their own fork.  Otherwise they won't be able to store their repo with a git push, or issue pull requests to you easily for commits to dorothy that should be shared by others.

Instead of:

```
(implicit 'mkdir myblog' not mentioned)
$ cd myblog
$ git clone git://github.com/cloudhead/dorothy.git .
$ heroku create
$ git push heroku master
```

Better:

```
$ git clone git://github.com/cloudhead/dorothy.git myblog      ## no mkdir needed
$ heroku create <myblogname>      ## creates myblogname.heroku.com
$ git push heroku master
```

This approach does not allow for pushing changes easily back to github, where others can benefit from them.  A git push would fail since its origin is cloudhead's account.

Best:

```
Fork the github dorothy repo from : http://github.com/cloudhead/dorothy
$ git clone git://github.com/YOUR-GITHUB-UNAME/dorothy.git myblog      ## no mkdir needed
$ heroku create <myblogname>      ## creates myblogname.heroku.com
$ git push heroku master
$ git push     ## pushes everything, including changes to be shared back to github 
```

**Comment by cloudhead** [comment]
Oh great, I'll update the site with the shorter version.

As far as forking is concerned, you don't really _need_ to push changes back to github, you can use heroku as your canonical repo. So I think I'll leave that as an option, and maybe mention it somewhere.

**Comment by grempe** [comment]
If you were to lose a disk, can you clone a fresh repo _from_ Heroku in addition to pushing?  I have not seen this done, but maybe I missed it.

If not, then keeping another clone on github is a good idea.

**Comment by ghost** [comment]
grempe: You can clone directly from Heroku :)
Some info: http://docs.heroku.com/sharing

git clone -o heroku git@heroku.com:appname.git
