### ISSUE TITLE
Feed should only show the latest few articles, not all articles

### ISSUE THREAD

**Issue by ghost** [cloudhead/toto#17]
Feedburner just stopped working for my blog because the feed is too large since it's loading all the blog's articles. Feed is there to show latest updates, not archives, so should only load up a few latest posts. Modifying the feed builder with the following to fetch the last 10 articles:

<code>articles[-10, 10].each do |article|</code>

Still waiting for Feedburner to refresh, will let you know if this works.

**Comment by ghost** [comment]
Yeah, this did it. Make sure to update the builder in dorothy for the next update.

**Comment by ghost** [comment]
Even better:

<pre>articles.reverse[0..10].each do |article|</pre>

Show them in the right order

**Comment by nogweii** [comment]
i think this is fixed in the latest push to dorothy now?

**Comment by cloudhead** [comment]
oh yes, indeed! closing..
