### ISSUE TITLE
utf-8

### ISSUE THREAD

**Issue by chikamichi** [cloudhead/toto#20]
Hi.

It seems like toto doesn't handle utf-8 correctly yet (at least it's broken for me ;). I did not look through the code yet, just to let you know about it.

**Comment by cloudhead** [comment]
Hmm is it rdiscount/markdown which doesn't support utf8? I'll look into it.

**Comment by simonedamico** [comment]
The same here, can't put è in the articles.

**Comment by simonedamico** [comment]
Ok the problem was in dorothy not in toto. I pull the commit to fix-it.
It was a problem of html econding document :D

**Comment by cloudhead** [comment]
haha.

Thanks, pulled it in.
