### ISSUE TITLE
Let archives list be available in all sub pages

### ISSUE THREAD

**Issue by MikeAbner** [cloudhead/toto#26]
I'd like to have the archives list be in the layout.rhtml file so that I can have a sidebar with all of the archives when you are on any page.  But if I do that and navigate to the about page I get a rack exception saying that the archives variable is empty.

**Comment by MikeAbner** [comment]
This also applies to the individual article pages as well.  The dorothy app has the archives in the index.rhtml template, but i'd like to move it to layout.rhtml.

**Comment by ghost** [comment]
All articles are available to all pages, including layout. Instead of archives use @articles to call them.

**Comment by MikeAbner** [comment]
Excellent.
