### ISSUE TITLE
Add support for metadata and description tags for SEO

### ISSUE THREAD

**Issue by MikeAbner** [cloudhead/toto#27]
Add tags to the header section of each article to support SEO metadata keywords and description.

Title: My blog post
Date: 11/02/2010
keywords: blog, post, toto, github, blah
description: How to set up a blog using toto and Heroku

<text of article>

**Comment by ghost** [comment]
Good idea. Maybe add default keywords/description in config + add a variable into the layout file. It will use default if nothing is specified.

**Comment by cloudhead** [comment]
good idea.

**Comment by nogweii** [comment]
Doesn't this relate to issue #25 as well?

**Comment by cloudhead** [comment]
We figued this out with dmitry, it's actually pretty easy with the default install:

In the layout file, you get access to a `@context` var, which holds the relevant article information. You can pull the metadata out of there, and put it wherever you want.

**Comment by ghost** [comment]
Here's the code:

<pre>
&#60;meta name="description" content="&#60;%= @context[:description] || 'Default description goes here if the description meta is unavailable' %&#62;" /&#62;
</pre>
