### ISSUE TITLE
Custom template engines

### ISSUE THREAD

**Issue by peterberkenbosch** [cloudhead/toto#3]
I would love to us toto for my small corporate site, I tried to build the blog index page inside a "blog" page. This does not work, seems that only index has access to the articles variable?

So my goal is to have a blog on http://127.0.0.1/blog/

How could I achieve that?

**Comment by cloudhead** [comment]
Hey, I'm gonna add this feature through a config var probably, but for now, you could alias :index to :blog by adding this code to your `config.ru`:

```
class Toto::Site
  alias :blog :index
end
```

This will make them identical, but will show up as `/blog` in the url.

**Comment by peterberkenbosch** [comment]
Brilliant! That works as a charme... Love this..

Need to polish my Sinatra code-fu, would love to add compass support with haml/sass/blueprint etc.. what's your take on that? 

Could it be made extendable so the toto core stay's lean and mean.

Peter.

**Comment by cloudhead** [comment]
Additional preprocessing, like Sass could probably be handled by a Rack middleware — I'm sure someone already wrote something like that.

For templating, I'd have to expose the template engine, which is something I could do pretty easily through a config var, or at least make it really easy to monkey-patch. You can get that functionality right now though by overwriting this:

http://github.com/cloudhead/toto/blob/master/lib/toto.rb#L22-25

by something which calls haml.

**Comment by peterberkenbosch** [comment]
cool.. thanks.. I will give it a shot this weekend...

**Comment by cloudhead** [comment]
incidently, just pushed 0.2.6, which gives access to `@articles` from all pages — for your scenario, I still think the alias makes more sense, because /blog is actually the index.

note that `@articles` is lazy-loading, so it won't load the actual articles until you try to access a property of it.

**Comment by peterberkenbosch** [comment]
nice! 

Found how to use sass : 
  use Sass::Plugin::Rack

it's already there in the haml gem... :)

**Comment by peterberkenbosch** [comment]
And this for Haml processing

module Toto
  module Template
    def to_html page, &blk
      path = (page == :layout ? Paths[:templates] : Paths[:pages])
      Haml::Engine.new(File.read("#{path}/#{page}.haml"),:attr_wrapper => '"', :filename => path ).render(binding)
    end
  end
end

**Comment by cloudhead** [comment]
nice. I think giving the ability to pass a rendering lambda to the config would be ideal in this case, something like:

```
set :renderer, lambda do |page| 
    Haml::Engine.new(File.read("#{path}/#{page}.haml"),:attr_wrapper => '"', :filename => path ).render(binding)
end
```

and then evaluating it in to_html.

could open up lots of possibilities.

**Comment by cloudhead** [comment]
I just pushed `0.4.0`, which makes this possible through the `:to_html` setting:

```
set :to_html, lambda do |path, page, binding| 
    Haml::Engine.new(File.read("#{path}/#{page}.haml"),
                               :attr_wrapper => '"',
                               :filename => path ).render(binding)
end
```

I haven't tested with Haml specifically, but there's no reason it shouldn't work

**Comment by peterberkenbosch** [comment]
very nice!! Still haven't had time to finish my webpage with toto, but it's still in the pipeline. This feature is very a very nice addition.

**Comment by resistorsoftware** [comment]
I am trying to switch to Haml rendering and get this with the new code:
config.ru:29:in `lambda': tried to create Proc object without a block (ArgumentError)
    from config.ru:29
    from /var/lib/gems/1.8/gems/toto-0.4.0/lib/toto.rb:316:in`instance_eval'
    from /var/lib/gems/1.8/gems/toto-0.4.0/lib/toto.rb:316:in `initialize'

**Comment by resistorsoftware** [comment]
I am using the config.ru:

set :to_html, lambda { |path, page, binding| 
    Haml::Engine.new(File.read("#{path}/#{page}.haml"),
      :attr_wrapper => '"',
      :filename => page ).render(binding)
  }

but now Haml barks about things with a trace...

Traceback (innermost first)

/var/lib/gems/1.8/gems/haml-2.2.17/lib/haml/engine.rb: in eval
      eval(precompiled + ";" + precompiled_method_return_value,...
/var/lib/gems/1.8/gems/haml-2.2.17/lib/haml/engine.rb: in render
      eval(precompiled + ";" + precompiled_method_return_value,...
config.ru: in nil
    Haml::Engine.new(File.read("#{path}/#{page}.haml"),...
/var/lib/gems/1.8/gems/toto-0.4.0/lib/toto.rb: in call
      config[:to_html].call(path, page, binding)...
/var/lib/gems/1.8/gems/toto-0.4.0/lib/toto.rb: in to_html
      config[:to_html].call(path, page, binding)...
/var/lib/gems/1.8/gems/toto-0.4.0/lib/toto.rb: in render
        type == :html ? to_html(:layout, @config, &Proc.new { to_html page, @config }) : send(:"to_#{type}", :feed)

The dump of the lamda parameters:
 Path blog/templates, page layout, binding #Binding:0x7f47da9b4258

The File object is good.. represents layout.haml

**Comment by cloudhead** [comment]
ahm, it's just the `:filename => page` should be `:filename => path` — I have no idea what that does though.

gonna fix the example.

**Comment by resistorsoftware** [comment]
Excellent... Good eye... I missed that too when looking at the Haml docs. Works like a charm. Very nice having Haml templates!! W00t. Thanks!

**Comment by cloudhead** [comment]
np, just pushed an update to be able to pass blocks instead of lambdas, should be prettier:

```
set :to_html do |page|
   # do stuff
end
```
