### ISSUE TITLE
Toto should use the URL for an XML request as the name of the file

### ISSUE THREAD

**Issue by nogweii** [cloudhead/toto#30]
By default, it's hardcoded to `:feed`, which then causes errors when you trying to access any other .xml file, regardless if it exists. When trying to access these files, you get an exception: `NoSuchMethod 'articles' for Toto::Context`.

Already fixed in my fork, evaryont@74e4ffe55ddfaefc76f9e8561eadcca64124118d I've already submitted a pull request, as well.

**Comment by nogweii** [comment]
Ah, crap. There is an error with my code. Lemme fix it, it'll involve both dorothy and toto, I think.

**Comment by nogweii** [comment]
Ah, I finally fixed this one. Should work with latest head on evaryont/toto and evaryont/mindtables

**Comment by cloudhead** [comment]
fixed/pulled — I had to fix the tests and doc, it might break for some people who have a feed.builder. But I think the new way is more flexible.
