### ISSUE TITLE
Wordpress to Toto Converter

### ISSUE THREAD

**Issue by jweissman** [cloudhead/toto#35]
I'm pretty sure this isn't really the right place, but I've developed a little wordpress-WXR-to-Toto-articles converter. It's in Python and I'm guessing it might eventually be useful to someone. A pastie is here (http://pastie.org/876755).

**Comment by cloudhead** [comment]
Hey, thanks, I'll put it in the wiki!

**Comment by cloudhead** [comment]
I took the liberty to put it in a gist on github, and added it to the wiki.
