### ISSUE TITLE
Hosting on http://domain.tld/blog/

### ISSUE THREAD

**Issue by jpluscplusm** [cloudhead/toto#36]
I can't quite see how to make stock toto/dorothy host on /blog/, where the path is virtual.  Things that break include: the links to individual articles from the index page (as they use .path instead of any part of config[:url]), links inside index.xml, and links to the css on the article pages.

I've cloned both projects at http://github.com/jpluscplusm/(toto|dorothy) with minor changes that make this possible, and would appreciate either a merge, or a suggestion of how better to achieve it with the existing code&config.ru.  Apologies if this isn't the recognised git-ish way of requesting/suggesting a merge - I'm using this project to learn git :-)

HTH,
Jonathan

**Comment by davejacobs** [comment]
Alexis,

I've seen your comment [indicating support for this option](http://github.com/jpluscplusm/toto/commit/0df95e04a6b46e002b8f0a60bd67b0012dce2805#commitcomment-56938), but I haven't seen a commit to the master branch yet. Any word on when that will be in the gem?

David

**Comment by cloudhead** [comment]
Merged into master (`0.4.5`).

Setting is `:prefix`, set it to 'blog' in this case
