### ISSUE TITLE
Confusion: Should :prefix include the leading slash?

### ISSUE THREAD

**Issue by nogweii** [cloudhead/toto#38]
Currently, if you do `set :prefix, "blog"` the string "blog" is literally appeneded, without the leading slash.

Personally, I was expecting "/blog/2010/..." but instead I got "blog/2010/...". Is this the intended behaviour? If so, perhaps it should be better documented?

**Comment by cloudhead** [comment]
hmm yea that's not right.. it should work as expected, with either `blog` or `/blog` or even `/blog/`

The `/` should be added automatically, and we can do something like `prefix.delete('/')`
