### ISSUE TITLE
Textile support?

### ISSUE THREAD

**Issue by brandonweiss** [cloudhead/toto#41]
Any chance of support for Textile alongside Markdown?

**Comment by billymeltdown** [comment]
Aye, I'd like to see that myself. Just checking in here to see if anybody is already working on it, figured it would be worth a little hacking time.

**Comment by sdesbure** [comment]
Hi, a dirty way to do that is the following:
- Add Redcloth in config.ru and say toto to use it:
    require 'redcloth'
    Markdown = RedCloth
- Say toto not to use "smart" mode of markdown (irrelevant for redcloth)  
    set :markdown, true

I think it would be good to have a better way to do that. I will try to propose a patch on that.
