### ISSUE TITLE
Mounting toto inside of a Rails 3 app

### ISSUE THREAD

**Issue by brandonweiss** [cloudhead/toto#52]
I've spent the last several days trying to figure out how to mount toto inside of a Rails 3 app. I've seen all the simple examples from Yehuda and others about how to mount simple Sinatra or Rack apps, but in all of them the app is so small that it's literally defined right there in the routes file or just a single file under app/metal. What I couldn't find was any documentation or examples for anything more complicated than that.

After trying everything I could think of and failing, I eventually found the [wiki page](http://wiki.github.com/cloudhead/toto/integrated-toto-and-a-rails-app-in-10-steps) and [this post](http://respond-to-blog.heroku.com/2010/02/12/integrating-toto-and-rails/) that it was based on.

Is that really the only way to integrate toto into a Rails app? Doesn't that kind of defeat the purpose of being able to mount apps to begin with? Is it not possible to keep toto separate and just mount it via the Rails router? It seems ridiculous that you have to actually create a whole new rack app to route requests to the Rails app or toto.

**Comment by ixti** [comment]
I don't see any problems to simply add another app into config.ru of Rails 3.
Here're steps to create and run a dummy Rails 3 app with toto:
- `$ cd /tmp`
- `$ rails new hommerr && cd hommerr`
- `$ git clone git://github.com/cloudhead/dorothy.git`

Now put following contents under `/tmp/hommerr/config.ru` of rails app:

``` ruby
require ::File.expand_path('../config/environment',  __FILE__)
require 'toto'

Toto::Paths[:templates] = "dorothy/templates"
Toto::Paths[:pages]     = "dorothy/templates/pages"
Toto::Paths[:articles]  = "dorothy/articles"

toto = Toto::Server.new do
  set :author,      "Aleksey V. Zapparov AKA ixti"
  set :title,       "Hommerr Dummy Blog"
  set :url,         "http://example.com"
  set :markdown,    :smart
  set :prefix,      "blog"
end

map '/blog' do
  run toto
end

map "/" do
  run Hommerr::Application
end
```

**Comment by brandonweiss** [comment]
This was a long time ago. Can't remember what happened, but that either didn't work, or I was just doing something wrong. Going to close this ticket.

**Comment by lgs** [comment]
@ixti : that works fine for me, 
thanks for shearing ;-)

... this is my way to index css layout too :

<pre>
# This file is used by Rack-based servers to start the application.

require ::File.expand_path('../config/environment',  __FILE__)
require 'toto'

# Rack config
use Rack::Static, :urls => ['/css', '/js', '/images', '/favicon.ico'], :root => './toto-blog/public'
use Rack::CommonLogger

if ENV['RACK_ENV'] == 'development'
  use Rack::ShowExceptions
end

Toto::Paths[:templates] = "toto-blog/templates"
Toto::Paths[:pages]     = "toto-blog/templates/pages"
Toto::Paths[:articles]  = "toto-blog/articles"

toto = Toto::Server.new do
  set :author,      "Luca G. Soave"
  set :title,       "GitWatcher Blog"
  set :url,         "http://localhost:3001/"
  set :markdown,    :smart
  set :prefix,      "blog"
end

map '/blog' do
  run toto
end

map "/" do
  run Rails3MongoidOmniauthSimple::Application
end
</pre>


my toto is in ~/my-rails-app/toto-blog
