### ISSUE TITLE
First installation fails

### ISSUE THREAD

**Issue by calderon** [cloudhead/toto#63]
Hi! I try to use Toto at Heroku. I follow the how-to posted at toto's web. But something went wrong. After "heroku logs":

/usr/ruby1.8.7/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': /home/slugs/361474_6b9b23f_7bfb-e9a95e2f-8924-4114-a344-c508ff3622c4/mnt/.gems/gems/toto-0.4.7/lib/toto.rb:100: syntax error, unexpected '\n', expecting '=' (SyntaxError)

...and a lot of lines more. I try on local, with unicorn. Same errors.

**Comment by dotnetdan** [comment]
I am having the same problem.. however, when I run locally using thin, it works perfectly.  I double checked that I am following the steps from the toto website many times, still same problem.  I'm running Ruby191 on Windows.

**Comment by calderon** [comment]
The version 0.4.6 works

**Comment by doshdosh** [comment]
I'm getting a similar error in Ubuntu 10.10. Did someone find a solution for this?

**Comment by daviding** [comment]
Yes, I'm stuck too. Works locally but fails with the toto.rb:338 syntax error. Ruby version, perhaps Heroku settings?

EDIT: Yes, that fixes it, move to ruby 1.9.2 on Heroku with this:

heroku stack:migrate bamboo-mri-1.9.2

Hope that helps someone else

**Comment by cloudhead** [comment]
Yea, there's an error when using ruby 1.8— switching to 1.9 fixes it, as shown by daviding.

I just pushed a new version of the gem, 0.4.9 — which should fix the errors in 1.8. Please give it a try.

**Comment by ixti** [comment]
@cloudhead I believe this issue can be closed :))

**Comment by cloudhead** [comment]
hah indeed.
