### ISSUE TITLE
Parse titles with markdown

### ISSUE THREAD

**Issue by ghost** [cloudhead/toto#7]
e.g. turn -- into "—" in titles?

**Comment by jamesarosen** [comment]
This works great:
    <html>
      <body>
        <h2>Some Title &mdash; With an Em-Dash</h2>
        ...

This doesn't:
    <html>
      <head>
        <title>Some Title &mdash; With an Em-Dash</title>
        ...

**Comment by ghost** [comment]
I was thinking the post rather than page titles :)

**Comment by nogweii** [comment]
You can call the `markdown` method in the templates, so you can do `<%= markdown article.title %>`

**Comment by cloudhead** [comment]
Yea, I'd rather not have this as the default behaviour, so evaryont's solution is best.
