### ISSUE TITLE
NoMethodError: undefined method `slugize' for nil:NilClass 

### ISSUE THREAD

**Issue by timrombergjakobsson** [cloudhead/toto#74]
Hi!
I installed Toto some while ago and started using it and loving it. I was using it with Ruby 1.8.7 and using shotgun as server. Yesterday I managed to get rvm working and installed Ruby 1.9.3 and now when I try to run the shotgun server or push to heroku Im getting the error message mentioned in the title. When I did the heroku logs I got this error: !! Unexpected error while processing request: undefined method `slugize' for nil:NilClass. Which is basically the same Im getting when I run the server. I switched back to 1.8.7 so that I have all the gems and all but it still does not work. And now my app at Heroku is not available. Anyone got any clue on this one?? Thanks!
Regards 
Tim

**Comment by ixti** [comment]
Please provide full trace (with both Ruby 1.8.7 and 1.9.3).

**Comment by timrombergjakobsson** [comment]
This

**Comment by ixti** [comment]
Sorry, but seems like you have forgot to attach it.
I run my toto with 1.9.2 normally, but today I have installed 1.9.3-preview1 (latest available release) and it works fine.

**Comment by timrombergjakobsson** [comment]
You are so right. Was an old issue now resolved since long time. Thanks for the feedback!

**Comment by ixti** [comment]
Ah! That's great! :))
