### ISSUE TITLE
Feature Request: Search Functionality

### ISSUE THREAD

**Issue by proffalken** [cloudhead/toto#75]
Hi is there any way to (or are there any plans to add) search the blogs created using Toto?

I'd be very interested in helping to add this if others can guide me (my Ruby is less than good...)

Thanks,

PF

**Comment by BPScott** [comment]
I'd say search is outside the scope of Toto, but you could use a [Google Custom Search](http://www.google.com/cse/).

**Comment by proffalken** [comment]
ok, thanks, I'll take a look.
