### ISSUE TITLE
about directories in "public"

### ISSUE THREAD

**Issue by afknapping** [cloudhead/toto#77]
i created new folders inside "public":
- js
- typefaces
- prc
- images
- test

"js" and "images" are recognized and usable. i can link to files inside of them and when calling /js/ or /images/ i get a file not found error.

but the others, like /test/, produce a 404-error.

i would be thankful for a hint in the right direction.

**Comment by 5v3n** [comment]
Have a look at dorothy's default `config.ru`:

https://github.com/cloudhead/dorothy/blob/master/config.ru

```
# Rack config
use Rack::Static, :urls => ['/css', '/js', '/images', '/favicon.ico'], :root => 'public'
```

You have to introduce any directory you want to make available via your public root. The two usable ones are already addressed here, for adding the rest use

```
# Rack config
use Rack::Static, :urls => ['/css', '/js', '/images', '/prc', 'test', 'typefaces', '/favicon.ico'], :root => 'public'`
```

Guess that will do the trick.

Glad you're having a look at the tiniest blogging engine in Oz - enjoy!

Sven Kräuter | 5v3n

**Comment by afknapping** [comment]
thx a lot!

**Comment by afknapping** [comment]
didn't close.
