### ISSUE TITLE
Add a default config.ru file

### ISSUE THREAD

**Issue by jamesarosen** [cloudhead/toto#9]
The file isn't in the source, but nor is it in `.gitignore`. Was it simply omitted or was there a reason for not versioning/sharing the file?

**Comment by cloudhead** [comment]
because `toto` is the actual library, the config.ru isn't included here, but instead is included with `dorothy`, the default template : http://github.com/cloudhead/dorothy

**Comment by jamesarosen** [comment]
I somehow missed that distinction in the README.

**Comment by cloudhead** [comment]
yea, it should probably be more explicit in the README.

**Comment by cloudhead** [comment]
updated README
