### ISSUE TITLE
[low priority] Genrate static website

### ISSUE THREAD

**Issue by ixti** [cloudhead/toto#99]
This is just  crazy (and probably useless) idea. Toto based website is in fact basically static, so we can have a special rake task which will generate "static" version of website, so that would be possible to use with almost any hosting platform :)) and with gh-pages of github as well.

**Comment by guidoism** [comment]
I don't think that this is crazy at all. I think toto is awesome, but it does seem really weird that it doesn't do this by default. It makes a lot of sense to generate a static website and publish it onto s3.

**Comment by AndrewVos** [comment]
You could write up a script to do this in a few minutes with ruby or bash even.

**Comment by ixti** [comment]
@AndrewVos well, it is. I can't say it's a few minutes task. But I agree it can be easily written. Basically it was some kind of rfc in order to determine for myself is it a good idea or not. Now I know that I'm not the only one who was thinking about it :))

**Comment by benjamincharity** [comment]
This sounds like an amazing idea.  Publishing a toto site to S3 would definitely be my preference!  I'll be watching!

**Comment by AndrewVos** [comment]
Why not just use a static site generator then? There's like ten
million if them? Try octopress.

On 19 Oct 2011, at 05:08, Benjamin Charity
reply@reply.github.com
wrote:

**Comment by ixti** [comment]
I can't say for everyone, but I feel two opposite feelings about such static generators. So first I would like to anser Andrew's question... I don't want to use Jekyll, because I don't like it's structure. To be honest now I realize that I want a little bit different structure of files even for toto (and I'll repspect my wish in my own blog if I'll have time to sit down and write it) - I can surf them without web and as I use my blog mostly to write down things I don't want to forget - that's pretty useful for me (to have good structure, which is goodlooking as well :)).

Why I might want static site generator? Because it would be possible to deploy static website on any hosting and it will be just faster than anything. On another hand I might want to still have dynamic site and it seems easier to me to modify such code.

After all right now I relized, that either I'm pregnant, or probably got sick. I can't decide what I like more :)) static site seems to me good solution because it requires only plain HTTP server, so it cn be hosted anywhere. Dynamic site seems to me good solution because it fun and keeps directory clean (out of compiled things and so on)...

So, I guess, after all I think that static site generator is good thing. So providing an easy way to call precompiler will be nice thing :)) But I don't think it will be implemented in toto :)) So closing an issue.

**Comment by kvervo** [comment]
Even if this issue is closed, i would to say that I've been trying out toto. 
If toto would generate Static Websites, I will definitely used instead of octopress. Toto is much simpler and nicer to use.
So, I definitely in favor of the rake task for static content generation.
